project:
  type: website
  output-dir: docs

website:
  title: "Demetri Pananos Ph.D"
  site-url: https://dpananos.github.io
  repo-url: https://github.com/Dpananos/dpananos.github.io
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@PhDemetri"
    card-style: summary_large_image
  navbar:
    right:
      - text: About
        file: about.qmd
      - text: Consulting
        file: consulting/index.qmd
      - text: AI
        file: ai/index.qmd
      - icon: github
        href: https://github.com/Dpananos
      - icon: twitter
        href: https://twitter.com/PhDemetri
format:
  html:
    theme: flatly
    css: styles.css
