---
title: On Climbing Hills
date: 2025-10-15
code-fold: true
echo: true
fig-cap-location: top
categories: []
number-sections: false
draft: false
cache: true
---


I've been climbing this hill for what feels like a long time.  I can look back and see how high I've climbed, the rocks I've had to overcome, and the gullies I nearly was trapped in. But as I look forward, all I see is more hill.

A lot of people are on this hill with me.  Some are climbing with me, some are on other paths and we are just meeting either by accident or because this climb was more interesting to them.  Some people don't appreciate how far we've climbed, how much effort we had to give to get here.

I'm a little tired of climbing.  I'd like to set up camp on this part of the hill, but I have wound up coupling my livelihood to climbing.  I pay bills by climbing, and sometimes I need to climb hills I don't really like, or am not qualified to climb.  That really drains my energy for the main climb, making me want to rest even more.

The inability (or perhaps, desire to avoid) rest has made me irritable.  When people ask me questions about climbing, I get short with them.  I think I know a lot about climbing and am unable to be humble when someone shows me they are slightly higher on the hill than I am.

Some days, I don't climb at all.  But I think to myself, if I am not a climber then who am I?

I've learned a lot from climbing, but the remainder of the hill (should it ever end) is steeper.  It might be time to find another hill, and bring the experience I've made on this one to a new path.  New rocks, new gullies.  Not sure when, but hopefully soon.