---
title: Analysis of Paired Ordinal Data -- More Than the T-Test
date: 2026-03-27
code-fold: false
echo: false
fig-cap-location: top
categories: []
number-sections: false
draft: true
cache: false
format:
  html:
    html-math-method: mathjax
---

This post is going to really belabor a point, so if you came for a quick read, this is not the post for you.  Here is the TL;DR

::: {.callout collapse="false"}
## TL;DR

If you use ordinal regression and a cluster robust standard error, then you can benefit from the correlation in ordinal outcomes much like in a paired t-test.
:::

When answers are cheap, sometimes it pays dividends to really scrutinize the details. In this post I plan to do that.  We'll re-derive some basic results and take the long way to analyzing paired continuous data.  Then, we'll discuss how this can be paired to ordinal data and why that might matter (as a teaser, this can be applied to LLM Evals, at least in the way I've seen them done).

## Paired Data

Let the $y_{c, k}$ be some continuous outcome from the $k^{th}$ observation in pair $c$.  The $c^{th}$ pair is then $(y_{c, 1}, y_{c, 2})$.  If we want to test the null hypothesis that $E[y_{c, 1}] = E[y_{c, 2}]$ then the typical advice is to use a paired t-test.

The paired nature of the data leverages any correlation between the two observations to (hopefully) reduce the width of the confidence interval. This can readily be seen by computing the variance of the within-pair difference
$$
\beta_c = y_{c, 2} - y_{c, 1}.
$$

$$
\operatorname{Var}(\beta_c) = \operatorname{Var}(y_{c, 2}) + \operatorname{Var}(y_{c, 1}) - 2\operatorname{Cov}(y_{c, 2}, y_{c, 1})
$$

If the two are not negatively correlated then $\operatorname{Var}(\beta_c) \leq \operatorname{Var}(y_{c, 2}) + \operatorname{Var}(y_{c, 1})$, and therefore the confidence intervals are smaller than had the data been treated as not paired.

Rather than treating the two samples separately, we can view the problem as estimating the mean of these paired differences. Let
$$
\beta = E[\beta_c]
$$
denote the population average difference.

A natural estimator is then
$$
\hat\beta = \frac{1}{n}\sum_{c=1}^n \beta_c = \bar{y}_2 - \bar{y}_1 \>.
$$

The variance can be estimated as

$$
\widehat{\operatorname{Var}}(\hat\beta)
=
\frac{1}{n(n-1)} \sum_{c=1}^n \left[(y_{c,2} - y_{c,1}) - (\bar{y}_2 - \bar{y}_1)\right]^2
$$

which has a cleaner interpretation as the variance of the $\beta_c$ about their mean

$$
\widehat{\operatorname{Var}}(\hat\beta)
=
\frac{1}{n(n-1)} \sum_{c=1}^n (\beta_c - \hat\beta)^2 \>.
$$


This seems like a lot of ink to spill on what feels like a simple topic, but I promise this is important and we will come back to it in the next section.


## Paired T-test and Regression Equivalence

It is often noted that the same inference obtained from a (non-)paired t-test can also be recovered from a regression model. The natural question is: can we obtain the result of a paired t-test from a regression *without* first taking differences? The answer is yes, provided we treat each pair as a cluster and use a cluster-robust standard error.

Let $c \in \mathcal{C}$ index clusters (here, pairs), and let $X$ be the design matrix with a column of ones for the intercept and an indicator $\mathbb{I}(k=2)$. If we adopt the convention that the observation with $k=2$ is always the second row, then

$$
X_c =
\begin{bmatrix}
1 & 0 \\
1 & 1
\end{bmatrix}
\quad \forall c \in \mathcal{C},
$$

and

$$
y_c =
\begin{bmatrix}
y_{c,1} \\
y_{c,2}
\end{bmatrix}
\quad \forall c \in \mathcal{C}.
$$

The cluster-robust variance estimator is then

$$
\hat V(\hat \beta)
=
(X^\prime X)^{-1}
\left(
\sum_{c \in \mathcal{C}} X_c^\prime \hat \Omega_c X_c
\right)
(X^\prime X)^{-1}.
$$

Let's see what each component simplifies to. Since each cluster contributes the same $X_c$, we have

$$
X^\prime X = \sum_{c \in \mathcal{C}} X_c^\prime X_c
=
n
\begin{bmatrix}
2 & 1 \\
1 & 1
\end{bmatrix},
$$

which implies

$$
(X^\prime X)^{-1}
=
\frac{1}{n}
\begin{bmatrix}
1 & -1 \\
-1 & 2
\end{bmatrix}.
$$

Let $\hat e_c = y_c - X_c\hat \beta = \begin{bmatrix} y_{c, 1} - \bar y_{c, 1}, y_{c, 2} - \bar y_{c,2} \end{bmatrix} ^ \prime$.  Then

$$ X_c^\prime \hat e_c = \begin{bmatrix} y_{c, 1} - \bar y_{c, 1} \\ (y_{c, 1} - \bar y_{c, 1}) +  (y_{c, 2} - \bar y_{c,2}) \end{bmatrix}$$

and 

$$  X^\prime_c\hat \Omega_c X_c = X^\prime_c \hat e_c \hat e_c ^\prime X_c = \begin{bmatrix}
\left[(y_{c,1} - \bar y_1) + (y_{c,2} - \bar y_2)\right]^2 &
\left[(y_{c,1} - \bar y_1) + (y_{c,2} - \bar y_2)\right](y_{c,2} - \bar y_2)
\\[6pt]
\left[(y_{c,1} - \bar y_1) + (y_{c,2} - \bar y_2)\right](y_{c,2} - \bar y_2) &
(y_{c,2} - \bar y_2)^2
\end{bmatrix}$$

Summing over $c$ and putting it all together

```{r}
#| include: false
library(fixest)
library(tidyverse)
Bigma <- matrix(c(1, 0.8, 0.8, 1), nrow=2)
Y <- MASS::mvrnorm(n=1000, mu=c(0, 0), Sigma = Bigma)

d <- tibble(y = c(Y[, 1], Y[, 2]),
            cluster_id = rep(1:1000, 2),
            k = rep(1:2, each=1000)
            )

# Non-clustered
f1 <- feols(y~k, data=d)
f2 <- feols(y~k, data=d, vcov = ~ cluster_id)

#paired analysis
f3 <- t.test(Pair(Y[, 2] , Y[, 1]) ~ 1)

paired <- broom::tidy(f3) |> 
  mutate(analysis = 'Paired') |> 
  select(analysis, estimate, conf.low, conf.high)

regressions <- list('Non-Clustered' = f1, 'Clustered' = f2) |> 
  imap_dfr(~{
    broom::tidy(.x, conf.int=T) |> 
      filter(term=='k') |> 
      mutate(analysis = .y) |> 
      select(analysis, estimate, starts_with('conf'))
  }) |> 
  arrange(analysis)


bind_rows(paired, regressions) |> 
  tinytable::tt(digits=4)
```

